### ISSUE TITLE
Change Animation

### ISSUE THREAD

**Issue by Bes79** [flame-engine/flame_flare#6]
Is any way to change animation speed?

**Comment by erickzanardo** [comment]
Use `stepTime` parameter

https://flame-engine.org/docs/images.md#animation

**Comment by renancaraujo** [comment]
This is more like a flare question. Ref to https://github.com/2d-inc/Flare-Flutter/issues/167

**Comment by erickzanardo** [comment]
Oh, sorry, I got confused on this.

**Comment by renancaraujo** [comment]
Im gonna close it for now. If something isn't clear, feel free to reopen it.
