### ISSUE TITLE
Image position deviation

### ISSUE THREAD

**Issue by bing6** [flame-engine/flame_flare#7]
![image](https://user-images.githubusercontent.com/8476017/90616432-03566780-e240-11ea-81d1-97a1592fc786.png)

**Comment by renancaraujo** [comment]
Tested the file exported from this animation on the example app and it seems ok. 

I'm closing since we dont have a single extra detail of your issue (code examples etc).

![](https://user-images.githubusercontent.com/6718144/90629104-ab573b00-e216-11ea-97bc-1c8f67da0bc1.jpeg)

**Comment by bing6** [comment]
Do you open it through iOS or Android simulator?
I still have problems here.

![image](https://user-images.githubusercontent.com/8476017/90712823-714d6e00-e2d6-11ea-8f1c-fb3e52f907af.png)
@renancaraujo

**Comment by renancaraujo** [comment]
> Do you open it through iOS or Android simulator?

Both.

I have to ask for:
The output of your flutter doctor?
Which file did you use to test?
Were you using the last version of the package?
