### ISSUE TITLE
After updating to latest flutter, flame causing problems

### ISSUE THREAD

**Issue by gnudles** [flame-engine/flame_flare#8]
Hello, few days ago I updated flutter, but then my flutter-flame project stopped working. (I am testing on linux)
I get the following error:
flutter: Another exception was thrown: 'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 311 pos 12: '!_debugDuringDeviceUpdate': is not true.
$ flutter doctor -v
[✓] Flutter (Channel master, 1.25.0-9.0.pre.57, on Linux, locale en_IL.UTF-8)
    • Flutter version 1.25.0-9.0.pre.57 at /home/orr/SDK/flutter
    • Framework revision f37969638d (32 hours ago), 2020-12-14 22:18:03 -0500
    • Engine revision 1749dbcc1b
    • Dart version 2.12.0 (build 2.12.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/orr/SDK/Android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /home/orr/SDK/Android
    • Java binary at: /home/orr/SDK/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.0
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.5)
    • Android Studio at /home/orr/SDK/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 87.0.4280.88 snap

when I remove the flame widget, it seems to be ok

**Comment by spydon** [comment]
The master channel of flutter is not supported (it breaks all the time), please use Stable or Beta.

**Comment by gnudles** [comment]
Thank you, but desktop support is not available on stable channel. channel dev seems to also cause problems
